### ISSUE TITLE
A question about the results of HyperIQA

### ISSUE THREAD

**Issue by chencn2020** [guanghaoyin/CVRKD-IQA#2]
Hi, there is something confuses me about the experiment results of HyerIQA in table 1, because I'm just a beginner in IQA.
The Srocc and Plcc results on TID2013 and KonIQ-10k are 0.686 0.721, 0.332 0.338 respectively, which is far from the results in original paper.
So, did you also retain the HyperIQA with multi-patches instead of following the original experiments settings?

**Comment by guanghaoyin** [comment]
Yes, our experimental setting is different from HyperIQA. For fair comparisons between FR/NR/NAR methods, we retrain those NR/NAR-IQA SOTAs following the commonly used experimental setting of FR-IQAs.  All NR/NAR-IQA SOTAs are retrained on synthetic Kaddid-10K and cross-evaluated on LIVE, CSIQ, TID2013, and KonIQ-10K.

**Comment by chencn2020** [comment]
懂了, 多谢(ㅅ´ ˘ `)
